CREATE TABLE IF NOT EXISTS phones.soti_import_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_filename TEXT,
    sync_token TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'processing',
    total_rows INTEGER NOT NULL DEFAULT 0,
    valid_rows INTEGER NOT NULL DEFAULT 0,
    invalid_rows INTEGER NOT NULL DEFAULT 0,
    created_rows INTEGER NOT NULL DEFAULT 0,
    updated_rows INTEGER NOT NULL DEFAULT 0,
    deactivated_rows INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT soti_import_run_sync_token_unq UNIQUE (sync_token),
    CONSTRAINT soti_import_run_status_chk CHECK (status IN ('processing', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS soti_import_run_status_idx
    ON phones.soti_import_run (status);

CREATE INDEX IF NOT EXISTS soti_import_run_started_at_idx
    ON phones.soti_import_run (started_at);

CREATE TABLE IF NOT EXISTS phones.soti_import_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_imei TEXT NOT NULL,
    device_name TEXT NOT NULL,
    assigned_user TEXT,
    model TEXT,
    route TEXT,
    registration_time TEXT,
    enrollment_time TEXT,
    connection_date TEXT,
    disconnection_date TEXT,
    phone TEXT,
    bssid_network TEXT,
    ssid_network TEXT,
    jira_ticket_id_raw TEXT,
    jira_ticket_id_normalized TEXT,
    custom_phone TEXT,
    custom_email TEXT,
    android_enter_email TEXT,
    location TEXT,
    import_run_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT soti_import_device_identity_device_unq UNIQUE (identity_imei, device_name)
);

CREATE INDEX IF NOT EXISTS soti_import_device_identity_imei_idx
    ON phones.soti_import_device (identity_imei);

CREATE INDEX IF NOT EXISTS soti_import_device_device_name_idx
    ON phones.soti_import_device (device_name);

CREATE INDEX IF NOT EXISTS soti_import_device_is_active_idx
    ON phones.soti_import_device (is_active);

CREATE INDEX IF NOT EXISTS soti_import_device_import_run_id_idx
    ON phones.soti_import_device (import_run_id);

CREATE INDEX IF NOT EXISTS soti_import_device_jira_ticket_id_normalized_idx
    ON phones.soti_import_device (jira_ticket_id_normalized);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'soti_import_device_import_run_fk'
    ) THEN
        ALTER TABLE phones.soti_import_device
            ADD CONSTRAINT soti_import_device_import_run_fk
            FOREIGN KEY (import_run_id)
            REFERENCES phones.soti_import_run (id)
            ON DELETE SET NULL;
    END IF;
END $$;
