CREATE TABLE IF NOT EXISTS phones.migration_phase_gate_control (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surface TEXT NOT NULL UNIQUE,
    source_mode TEXT NOT NULL DEFAULT 'legacy',
    threshold_profile TEXT NOT NULL,
    gate_owner TEXT NOT NULL,
    rollout_phase TEXT NOT NULL DEFAULT 'phase0',
    is_gate_open BOOLEAN NOT NULL DEFAULT false,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT migration_phase_gate_control_source_mode_chk
        CHECK (source_mode IN ('legacy', 'dual', 'canonical')),
    CONSTRAINT migration_phase_gate_control_threshold_profile_chk
        CHECK (threshold_profile IN ('reports', 'home', 'kpis', 'distributors'))
);

CREATE INDEX IF NOT EXISTS migration_phase_gate_control_rollout_phase_idx
    ON phones.migration_phase_gate_control (rollout_phase);

CREATE INDEX IF NOT EXISTS migration_phase_gate_control_is_gate_open_idx
    ON phones.migration_phase_gate_control (is_gate_open);

CREATE TABLE IF NOT EXISTS phones.migration_parity_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surface TEXT NOT NULL,
    period_start DATE,
    period_end DATE,
    baseline JSONB NOT NULL DEFAULT '{}'::jsonb,
    candidate JSONB NOT NULL DEFAULT '{}'::jsonb,
    delta JSONB NOT NULL DEFAULT '{}'::jsonb,
    delta_pct JSONB NOT NULL DEFAULT '{}'::jsonb,
    threshold_profile TEXT NOT NULL,
    passed BOOLEAN NOT NULL,
    operator TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT migration_parity_evidence_threshold_profile_chk
        CHECK (threshold_profile IN ('reports', 'home', 'kpis', 'distributors'))
);

CREATE INDEX IF NOT EXISTS migration_parity_evidence_surface_idx
    ON phones.migration_parity_evidence (surface);

CREATE INDEX IF NOT EXISTS migration_parity_evidence_threshold_profile_idx
    ON phones.migration_parity_evidence (threshold_profile);

CREATE INDEX IF NOT EXISTS migration_parity_evidence_passed_idx
    ON phones.migration_parity_evidence (passed);

CREATE INDEX IF NOT EXISTS migration_parity_evidence_created_at_idx
    ON phones.migration_parity_evidence (created_at);

INSERT INTO phones.migration_phase_gate_control (surface, source_mode, threshold_profile, gate_owner, rollout_phase, is_gate_open, notes)
VALUES
    ('reports_phones', 'legacy', 'reports', 'reports-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('reports_kpis', 'legacy', 'kpis', 'reports-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('home_kpis', 'legacy', 'home', 'dashboard-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('home_stock', 'legacy', 'home', 'dashboard-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('home_shipping', 'legacy', 'home', 'dashboard-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('distributors', 'legacy', 'distributors', 'stock-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('stock', 'legacy', 'home', 'stock-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.'),
    ('assignments', 'legacy', 'home', 'stock-eng-owner', 'phase0', false, 'Initialized by phase0 parity controls migration.')
ON CONFLICT (surface) DO NOTHING;
